### ISSUE TITLE
AttributeError: module 'rbdl' has no attribute 'loadModel'

### ISSUE THREAD

**Issue by artiuntelligence** [soshishimada/PhysCap_demo_release#7]
Thank you for sharing this great project.
I have been trying to replicate it but keep getting this error when running the demo:

Stage III running ... 
Traceback (most recent call last):
  File "pipeline.py", line 49, in <module>
    sim_loop(path_dict,floor_known=args.floor_known)
  File "/home/yang/Yifan/PhysCap_demo_release/stage3.py", line 26, in sim_loop
    model = rbdl.loadModel(path_dict["humanoid_path"].encode())
AttributeError: module 'rbdl' has no attribute 'loadModel'

I installed rbdl package according to the official website with no error but it still doesn't work. Hopefully you can give me some suggestion on that.

**Comment by soshishimada** [comment]
Hello. Can you try to compile rbdl (https://github.com/rbdl/rbdl) with the option "RBDL_BUILD_ADDON_URDFREADER " to be "ON"? Also, I recommend using rbdl v.2.6.0 when compilation.

**Comment by artiuntelligence** [comment]
Thank you for your help. I find out that I forget to add the rbdl python path to the environment variable. Now it can run without any problem.
